### ISSUE TITLE
Scrape timees out and scrape_timeout not configurable

### ISSUE THREAD

**Issue by marcusboden** [canonical/charm-prometheus-libvirt-exporter#32]
We're running into the issue that the scrape times out on machines with a lot of VMs. At the moment, I can only increase the scrape_timeout globally via the prometheus2 charm. I would like to have an option to increase the timeout for just the libvirt expoerter.

**Comment by Pjack** [comment]
We suggest to use the same timeout value between all exporters. There may be some performance issue that we need to get into more details.

**Comment by gabrielcocenza** [comment]
As a general recommendation is expected that long scrapes consider adding cache. The exporter itself seems that is archived so we need to decide if we fork the project and do this or maybe adopt a new exporter.
